name: Update F1

on:
  schedule:
    - cron: "0 6 * * 1"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-f1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install FastF1
        run: pip install fastf1

      - name: Update F1
        run: python f1/update.py

      - name: Commit changes
        run: |
          git config user.name "chitniskedar"
          git config user.email "chitniskedar7@gmail.com"

          git add README.md

          git diff --cached --quiet || git commit -m "update F1"

          git push
